services:
  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    container_name: "rabbitmq"
    env_file: .env
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./pvs/rabbitmq/data/:/var/lib/rabbitmq/
        - ./pvs/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - slot-machines-net

  mongodb:
    image: mongo:8.0.1
    container_name: "mongodb"
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./pvs/mongodb/data:/data/db
    networks:
      - slot-machines-net

  sm_manager:
    image: sm_manager:latest
    container_name: "sm_manager"
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      # DEBUG mount override
      - ./services/sm_manager/source:/sm_manager/source:rw
    networks:
      - slot-machines-net

  sm:
    image: sm:latest
    container_name: "sm"
    env_file: .env
    ports:
      - 8081:8080
    volumes:
      # DEBUG mount override
      - ./services/sm/source:/sm/source:rw
    networks:
      - slot-machines-net

networks:
  slot-machines-net:
    driver: bridge
